### ISSUE TITLE
Please, deploy @ genesisL1

### ISSUE THREAD

**Issue by alpha-omega-labs** [Udit-takkar/chess#2]
Hello!
Please deploy chess @ genesisL1 blockchain, thank you!

**Comment by Udit-takkar** [comment]
Actually some people might use chess engine and cheat to win matches and MATIC. 
Don't want anyone to be scammed.

**Comment by alpha-omega-labs** [comment]
genesisL1 is a layer1 blockchain for Art and Science! EVM one, but based on Cosmos SDK. Its NOT associated with money and is valueless by default! L1 is an utility token that is powering chain, please, take a look https://genesisL1.com https://genesisL1.io 
So please, don't hesitate and add (deploy) your magnificent web3chess dapp to genesisL1 chain. + Thank you!

**Comment by Udit-takkar** [comment]
Will do next month. currently busy somewhere.
I will contact you on twitter

**Comment by alpha-omega-labs** [comment]
Great! Take a look at other deployed - chess.genesisl1.org
will be great to have several chess dapps!
also there are plans to add p2p chat there, please join lounge tg https://t.me/Genesis_L1_Lounge

**Comment by Udit-takkar** [comment]
ok
